import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowRight, ArrowUpRight, Plus } from 'lucide-react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import SiteNav from '../components/SiteNav'
import Footer from '../components/Footer'
import { Button, EmptyState, SectionHeading } from '../components/ui'
import { getCourses } from '../lib/api'

const faq = [
  ['Is Trading Academy a trading or exchange platform?', 'No. Trading Academy is an educational platform. It does not execute trades, hold assets, provide investment recommendations, or promise financial outcomes.'],
  ['When do I get access to course content?', 'Protected learning content becomes available after your payment submission has been reviewed and approved by an authorized administrator.'],
  ['What payment networks are supported?', 'The active USDT payment methods configured by the administrator are shown on the payment page. Networks can include TRC20, BEP20, and ERC20.'],
  ['Can I learn at my own pace?', 'Yes. Lessons are organized into modules and your completion state is saved to your account, so you can return to your learning path whenever you are ready.'],
]

function ChartArt() {
  return <div className="hero-art"><div className="art-orbit"><i className="orbit-dot" /><i className="orbit-dot two" /></div><div className="art-panel"><div className="panel-top"><span>MARKET STRUCTURE / 01</span><span>LIVE STUDY</span></div><strong>Context before conviction.</strong><div className="chart"><svg viewBox="0 0 230 100" preserveAspectRatio="none"><defs><linearGradient id="chartFade" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#c8f05a" stopOpacity=".5" /><stop offset="1" stopColor="#c8f05a" stopOpacity="0" /></linearGradient></defs><path className="chart-area" d="M0 80 L19 71 L34 76 L48 52 L66 61 L83 34 L101 47 L118 18 L137 31 L156 24 L177 43 L198 16 L230 6 V100 H0 Z" /><path className="chart-line" d="M0 80 L19 71 L34 76 L48 52 L66 61 L83 34 L101 47 L118 18 L137 31 L156 24 L177 43 L198 16 L230 6" /></svg></div><span className="positive">+ Process over prediction</span></div></div>
}

export default function Home() {
  const [courses, setCourses] = useState([])
  const [openFaq, setOpenFaq] = useState(0)
  useEffect(() => { getCourses({ publishedOnly: true }).then(setCourses).catch(() => setCourses([])) }, [])
  const shownCourses = courses.slice(0, 3)
  return <div className="app-shell"><SiteNav /><main>
    <section className="hero"><div className="hero-grid" /><div className="container hero-content"><motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6 }}><span className="kicker">Market literacy, made deliberate</span><h1>Build a sharper <em>market mind.</em></h1><p className="hero-copy">A structured learning environment for people who want to understand markets with more context, better questions, and a process they can actually return to.</p><div className="hero-ctas"><Link to="/signup"><Button size="lg">Begin your learning path <ArrowRight size={15} /></Button></Link><a href="#about"><Button size="lg" variant="ghost">See how it works <ArrowDownRight size={15} /></Button></a></div><p className="hero-note">No hype · No financial promises · Education first</p></motion.div><motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .8, delay: .12 }}><ChartArt /></motion.div></div><div className="hero-foot"><div className="container ticker"><span><b>01</b> / STRUCTURE</span><span><b>02</b> / RISK LANGUAGE</span><span><b>03</b> / JOURNALING</span><span><b>04</b> / REPEAT</span></div></div></section>

    <section className="section section-paper"><div className="container"><SectionHeading eyebrow="The edge is a practice" title="Less noise. More signal." body="Trading Academy is built around the work that compounds: a consistent framework, useful vocabulary, and the habit of reviewing your own thinking." /><div className="value-grid"><motion.div className="value-card" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}><span className="index">01</span><h3>Learn the language.</h3><p>Make market concepts less abstract. Build a shared vocabulary for price, context, risk, and decision-making.</p></motion.div><motion.div className="value-card" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, delay: .1 }}><span className="index">02</span><h3>Study the structure.</h3><p>Follow concise lessons that move from foundations to frameworks without rushing past the why.</p></motion.div><motion.div className="value-card" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, delay: .2 }}><span className="index">03</span><h3>Keep your process.</h3><p>Track progress, return to lessons, and develop a repeatable study rhythm that belongs to you.</p></motion.div></div></div></section>

    <section className="section section-dark" id="about"><div className="container story-grid"><div className="story-aside"><div className="big-number">/03</div><span className="eyebrow">Inside the method</span><p>Progress is not a prediction. It is the evidence that your questions are getting better.</p></div><div><SectionHeading eyebrow="A considered curriculum" title="Designed for depth, not dopamine." body="A calmer learning experience for a subject that rewards patience. Work through the ideas, not the noise around them." /><div className="principles"><div className="principle"><span>01</span><div><h3>Frameworks over forecasts</h3><p>Understand how to inspect a market before you decide what it might do next.</p></div></div><div className="principle"><span>02</span><div><h3>Clarity over complexity</h3><p>Each course is structured to make hard ideas easier to revisit, explain, and apply to your own study.</p></div></div><div className="principle"><span>03</span><div><h3>Evidence over ego</h3><p>Learn to separate a strong thesis from a loud opinion—and document both with care.</p></div></div></div></div></div></section>

    <section className="section section-sage" id="courses"><div className="container"><SectionHeading eyebrow="The library" title="A curriculum you can grow into." body="Start with foundations, then keep widening your view. New course content can be added and organized by the Academy team through the admin workspace." /><div className="course-preview-grid">{shownCourses.length ? shownCourses.map((course, index) => <CoursePreview key={course.id || index} course={course} index={index} />) : <div className="home-empty-library"><EmptyState title="The course library is ready for your catalogue." body="Published courses added by the Academy team will appear here automatically." /></div>}</div><div style={{ marginTop: 26 }}><Link to="/courses"><Button variant="outline-dark">View the course library <ArrowRight size={14} /></Button></Link></div></div></section>

    <section className="section section-paper"><div className="container"><SectionHeading align="center" eyebrow="Your learning path" title="A simple loop that gets smarter." body="The platform keeps the mechanics out of the way so your attention can stay on the work." /><div className="process"><div className="process-step"><div className="process-dot">01</div><h3>Orient</h3><p>Choose a starting point and understand the terms.</p></div><div className="process-step"><div className="process-dot">02</div><h3>Study</h3><p>Move through short, focused lessons at your pace.</p></div><div className="process-step"><div className="process-dot">03</div><h3>Reflect</h3><p>Capture what made sense, and what still needs work.</p></div><div className="process-step"><div className="process-dot">04</div><h3>Return</h3><p>Build a durable practice through deliberate repetition.</p></div></div></div></section>

    <section className="section section-dark" id="faq"><div className="container"><SectionHeading align="center" eyebrow="Questions, answered" title="Make an informed start." body="A few important details before you create an account." /><div className="faq-list">{faq.map(([question, answer], index) => <div className={`faq-item ${openFaq === index ? 'open' : 'closed'}`} key={question}><button className="faq-question" onClick={() => setOpenFaq(openFaq === index ? -1 : index)}><span>{question}</span><Plus size={17} /></button><div className="faq-answer">{answer}</div></div>)}</div></div></section>
    <section className="cta-band"><div className="container cta-band-inner"><div><span className="eyebrow" style={{ color: 'rgba(17,21,18,.62)' }}>Start with intent</span><h2>Give your curiosity a curriculum.</h2></div><div><p>Build a steadier relationship with the ideas behind the market.</p><Link to="/signup"><Button variant="dark" size="lg">Create your account <ArrowUpRight size={15} /></Button></Link></div></div></section>
  </main><Footer /></div>
}

function CoursePreview({ course, index }) {
  return <motion.div className="course-card" initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, delay: index * .08 }}><div className="course-top"><span>0{index + 1} / COURSE</span><span>{course.level || course.difficulty || 'Core'}</span></div><div className="course-art"><span>{index === 0 ? 'BEGIN WITH CONTEXT' : index === 1 ? 'READ THE FRAME' : 'PRACTICE THE PROCESS'}</span></div><h3>{course.title || 'Untitled course'}</h3><p>{course.description || 'A structured course inside Trading Academy.'}</p><div className="course-bottom"><span>{course.duration_minutes ? `${course.duration_minutes} min` : 'Self-paced'}</span><Link className="arrow" to={`/courses/${course.id}`} aria-label={`Open ${course.title || 'course'}`}><ArrowRight size={14} /></Link></div></motion.div>
}
